// This file is auto-generated by sync-version.ts
export const APP_VERSION = "1.0.0";
export const LATEST_COMMIT_HASH = "8dbe94f";
export const CURRENT_BRANCH = "butler:[dev]";
export const BUILD_TIME = "2026-02-06T13:14:03.518Z";
