// This file is auto-generated by sync-version.ts
export const APP_VERSION = "1.0.0";
export const LATEST_COMMIT_HASH = "fc033f1";
export const CURRENT_BRANCH = "butler:[dev]";
export const BUILD_TIME = "2026-02-06T13:31:26.862Z";
