import { CLIENT_ENV, SERVER_ENV } from "'services/env";
import env from "#env";

const T3_CLIENT = CLIENT_ENV.of({
  CLOUDFLARE_TURNSTILE_SITE_KEY: env.VITE_CLOUDFLARE_TURNSTILE_SITE_KEY,
  HOST_URL: env.VITE_HOST_URL,
  POSTHOG_HOST: env.VITE_POSTHOG_HOST,
  POSTHOG_KEY: env.VITE_POSTHOG_KEY,
  POSTHOG_PROJECT_ID: env.VITE_POSTHOG_PROJECT_ID,
});

const T3_SERVER = SERVER_ENV.of({
  AUTHDB_DATABASE: env.AUTHDB_DATABASE,
  AUTHDB_PASSWORD: env.AUTHDB_PASSWORD,
  AUTHDB_READ_1: env.AUTHDB_READ_1,
  AUTHDB_READ_2: env.AUTHDB_READ_2,
  AUTHDB_USER: env.AUTHDB_USER,
  AUTHDB_WRITE: env.AUTHDB_WRITE,
  ENCRYPTION_KEY: env.ENCRYPTION_KEY,
  AXIOM_DATASET: env.AXIOM_DATASET,
  AXIOM_TOKEN: env.AXIOM_TOKEN,
  BETTER_AUTH_SECRET: env.BETTER_AUTH_SECRET,
  BETTER_AUTH_URL: env.BETTER_AUTH_URL,
  CLOUDFLARE_TURNSTILE_SECRET_KEY: env.CLOUDFLARE_TURNSTILE_SECRET_KEY,
  HOST_URL: env.HOST_URL,
  OIDC_ATHENAEUM_CLIENT_ID: env.OIDC_ATHENAEUM_CLIENT_ID,
  OIDC_ATHENAEUM_CLIENT_SECRET: env.OIDC_ATHENAEUM_CLIENT_SECRET,
  OIDC_ATHENAEUM_ISSUER: env.OIDC_ATHENAEUM_ISSUER,
  OIDC_IGS_CLIENT_ID: env.OIDC_IGS_CLIENT_ID,
  OIDC_IGS_CLIENT_SECRET: env.OIDC_IGS_CLIENT_SECRET,
  OIDC_IGS_ISSUER: env.OIDC_IGS_ISSUER,
  OIDC_VLG_CLIENT_ID: env.OIDC_VLG_CLIENT_ID,
  OIDC_VLG_CLIENT_SECRET: env.OIDC_VLG_CLIENT_SECRET,
  OIDC_VLG_ISSUER: env.OIDC_VLG_ISSUER,
  OTEL_EXPORTER_OTLP_ENDPOINT: env.OTEL_EXPORTER_OTLP_ENDPOINT,
  OTEL_EXPORTER_OTLP_HEADERS: env.OTEL_EXPORTER_OTLP_HEADERS,
  POSTHOG_HOST: env.POSTHOG_HOST,
  POSTHOG_KEY: env.POSTHOG_KEY,
  POSTHOG_PROJECT_ID: env.POSTHOG_PROJECT_ID,
  RESEND_API_KEY: env.RESEND_API_KEY,
  RESEND_FROM_EMAIL: env.RESEND_FROM_EMAIL,
  NODE_ENV: env.NODE_ENV,
});

export { T3_CLIENT, T3_SERVER };
