import { FileSystem, Path, Command } from "@effect/platform";
import { Console, Effect } from "effect";

export const syncVersion = Effect.gen(function* () {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;

  const pkgPath = path.resolve("package.json");
  const destPath = path.resolve("src/lib/version.ts");

  // 1. Package JSON lesen
  const pkgContent = yield* fs.readFileString(pkgPath);
  const pkg = yield* Effect.try({
    try: () => JSON.parse(pkgContent),
    catch: (error) => new Error(`Failed to parse package.json: ${error}`),
  });

  // 2. Git Commit Hash holen
  const commitHash = yield* Command.make(
    "git",
    "rev-parse",
    "--short",
    "HEAD",
  ).pipe(
    Command.string,
    Effect.map((s) => s.trim()),
    Effect.catchAll(() => Effect.succeed("unknown")),
  );

  // 3. Branch bestimmen (Normal vs. GitButler)
  const rawBranch = yield* Command.make(
    "git",
    "rev-parse",
    "--abbrev-ref",
    "HEAD",
  ).pipe(
    Command.string,
    Effect.map((s) => s.trim()),
    Effect.catchAll(() => Effect.succeed("unknown")),
  );

  let finalBranch = rawBranch;

  // Wenn GitButler genutzt wird (branch fängt mit gitbutler/ an)
  if (rawBranch.startsWith("gitbutler/")) {
    const butOutput = yield* Command.make("but", "branch", "--json").pipe(
      Command.string,
      Effect.map((s) => JSON.parse(s)),
      Effect.catchAll(() => Effect.succeed(null)),
    );

    if (butOutput && butOutput.appliedStacks?.[0]?.heads) {
      // Wir nehmen die Namen aller aktiven Heads im Stack und joinen sie
      const activeHeads = butOutput.appliedStacks[0].heads.map(
        (h: any) => h.name,
      );
      finalBranch = `butler:[${activeHeads.join(", ")}]`;
    }
  }

  // 4. Content generieren
  const versionContent = `// This file is auto-generated by sync-version.ts
export const APP_VERSION = "${pkg.version}";
export const LATEST_COMMIT_HASH = "${commitHash}";
export const CURRENT_BRANCH = "${finalBranch}";
export const BUILD_TIME = "${new Date().toISOString()}";
`;

  // 5. Schreiben
  yield* fs.writeFileString(destPath, versionContent);

  yield* Console.log(
    `✅ Version ${pkg.version} [${commitHash}] on ${finalBranch} synchronized.`,
  );
});
