/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTelemetryRouteImport } from './routes/api/telemetry'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as legalTermsRouteImport } from './routes/(legal)/terms'
import { Route as legalPrivacyPolicyRouteImport } from './routes/(legal)/privacy-policy'
import { Route as legalImpressumRouteImport } from './routes/(legal)/impressum'
import { Route as legalDigitalIndependenceRouteImport } from './routes/(legal)/digital-independence'
import { Route as legalCookiesRouteImport } from './routes/(legal)/cookies'
import { Route as error500RouteImport } from './routes/(error)/500'
import { Route as error404RouteImport } from './routes/(error)/404'
import { Route as error403RouteImport } from './routes/(error)/403'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as appSettingsRouteImport } from './routes/(app)/settings'
import { Route as appSessionsRouteImport } from './routes/(app)/sessions'
import { Route as appSecurityRouteImport } from './routes/(app)/security'
import { Route as appProfileRouteImport } from './routes/(app)/profile'
import { Route as appPrivacyRouteImport } from './routes/(app)/privacy'
import { Route as appDashboardIndexRouteImport } from './routes/(app)/dashboard/index'
import { Route as appAdminIndexRouteImport } from './routes/(app)/admin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as appAdminUsersRouteImport } from './routes/(app)/admin/users'
import { Route as appAdminSchoolsRouteImport } from './routes/(app)/admin/schools'
import { Route as appAdminAuditLogsRouteImport } from './routes/(app)/admin/audit-logs'
import { Route as appAdminUsersUserIdRouteImport } from './routes/(app)/admin/users.$userId'
import { Route as ApiUsersMeSessionsSessionIdRouteImport } from './routes/api/users/me.sessions.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelemetryRoute = ApiTelemetryRouteImport.update({
  id: '/api/telemetry',
  path: '/api/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const legalTermsRoute = legalTermsRouteImport.update({
  id: '/(legal)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const legalPrivacyPolicyRoute = legalPrivacyPolicyRouteImport.update({
  id: '/(legal)/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const legalImpressumRoute = legalImpressumRouteImport.update({
  id: '/(legal)/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const legalDigitalIndependenceRoute =
  legalDigitalIndependenceRouteImport.update({
    id: '/(legal)/digital-independence',
    path: '/digital-independence',
    getParentRoute: () => rootRouteImport,
  } as any)
const legalCookiesRoute = legalCookiesRouteImport.update({
  id: '/(legal)/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const error500Route = error500RouteImport.update({
  id: '/(error)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const error404Route = error404RouteImport.update({
  id: '/(error)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const error403Route = error403RouteImport.update({
  id: '/(error)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/(app)/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const appSessionsRoute = appSessionsRouteImport.update({
  id: '/(app)/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const appSecurityRoute = appSecurityRouteImport.update({
  id: '/(app)/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const appProfileRoute = appProfileRouteImport.update({
  id: '/(app)/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const appPrivacyRoute = appPrivacyRouteImport.update({
  id: '/(app)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardIndexRoute = appDashboardIndexRouteImport.update({
  id: '/(app)/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const appAdminIndexRoute = appAdminIndexRouteImport.update({
  id: '/(app)/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appAdminUsersRoute = appAdminUsersRouteImport.update({
  id: '/(app)/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const appAdminSchoolsRoute = appAdminSchoolsRouteImport.update({
  id: '/(app)/admin/schools',
  path: '/admin/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const appAdminAuditLogsRoute = appAdminAuditLogsRouteImport.update({
  id: '/(app)/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const appAdminUsersUserIdRoute = appAdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => appAdminUsersRoute,
} as any)
const ApiUsersMeSessionsSessionIdRoute =
  ApiUsersMeSessionsSessionIdRouteImport.update({
    id: '/api/users/me/sessions/$sessionId',
    path: '/api/users/me/sessions/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof appPrivacyRoute
  '/profile': typeof appProfileRoute
  '/security': typeof appSecurityRoute
  '/sessions': typeof appSessionsRoute
  '/settings': typeof appSettingsRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/403': typeof error403Route
  '/404': typeof error404Route
  '/500': typeof error500Route
  '/cookies': typeof legalCookiesRoute
  '/digital-independence': typeof legalDigitalIndependenceRoute
  '/impressum': typeof legalImpressumRoute
  '/privacy-policy': typeof legalPrivacyPolicyRoute
  '/terms': typeof legalTermsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/admin/audit-logs': typeof appAdminAuditLogsRoute
  '/admin/schools': typeof appAdminSchoolsRoute
  '/admin/users': typeof appAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof appAdminIndexRoute
  '/dashboard/': typeof appDashboardIndexRoute
  '/admin/users/$userId': typeof appAdminUsersUserIdRoute
  '/api/users/me/sessions/$sessionId': typeof ApiUsersMeSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof appPrivacyRoute
  '/profile': typeof appProfileRoute
  '/security': typeof appSecurityRoute
  '/sessions': typeof appSessionsRoute
  '/settings': typeof appSettingsRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/403': typeof error403Route
  '/404': typeof error404Route
  '/500': typeof error500Route
  '/cookies': typeof legalCookiesRoute
  '/digital-independence': typeof legalDigitalIndependenceRoute
  '/impressum': typeof legalImpressumRoute
  '/privacy-policy': typeof legalPrivacyPolicyRoute
  '/terms': typeof legalTermsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/admin/audit-logs': typeof appAdminAuditLogsRoute
  '/admin/schools': typeof appAdminSchoolsRoute
  '/admin/users': typeof appAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof appAdminIndexRoute
  '/dashboard': typeof appDashboardIndexRoute
  '/admin/users/$userId': typeof appAdminUsersUserIdRoute
  '/api/users/me/sessions/$sessionId': typeof ApiUsersMeSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/privacy': typeof appPrivacyRoute
  '/(app)/profile': typeof appProfileRoute
  '/(app)/security': typeof appSecurityRoute
  '/(app)/sessions': typeof appSessionsRoute
  '/(app)/settings': typeof appSettingsRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(error)/403': typeof error403Route
  '/(error)/404': typeof error404Route
  '/(error)/500': typeof error500Route
  '/(legal)/cookies': typeof legalCookiesRoute
  '/(legal)/digital-independence': typeof legalDigitalIndependenceRoute
  '/(legal)/impressum': typeof legalImpressumRoute
  '/(legal)/privacy-policy': typeof legalPrivacyPolicyRoute
  '/(legal)/terms': typeof legalTermsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/(app)/admin/audit-logs': typeof appAdminAuditLogsRoute
  '/(app)/admin/schools': typeof appAdminSchoolsRoute
  '/(app)/admin/users': typeof appAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(app)/admin/': typeof appAdminIndexRoute
  '/(app)/dashboard/': typeof appDashboardIndexRoute
  '/(app)/admin/users/$userId': typeof appAdminUsersUserIdRoute
  '/api/users/me/sessions/$sessionId': typeof ApiUsersMeSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/profile'
    | '/security'
    | '/sessions'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/403'
    | '/404'
    | '/500'
    | '/cookies'
    | '/digital-independence'
    | '/impressum'
    | '/privacy-policy'
    | '/terms'
    | '/api/health'
    | '/api/telemetry'
    | '/admin/audit-logs'
    | '/admin/schools'
    | '/admin/users'
    | '/api/auth/$'
    | '/admin/'
    | '/dashboard/'
    | '/admin/users/$userId'
    | '/api/users/me/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/profile'
    | '/security'
    | '/sessions'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/403'
    | '/404'
    | '/500'
    | '/cookies'
    | '/digital-independence'
    | '/impressum'
    | '/privacy-policy'
    | '/terms'
    | '/api/health'
    | '/api/telemetry'
    | '/admin/audit-logs'
    | '/admin/schools'
    | '/admin/users'
    | '/api/auth/$'
    | '/admin'
    | '/dashboard'
    | '/admin/users/$userId'
    | '/api/users/me/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/(app)/privacy'
    | '/(app)/profile'
    | '/(app)/security'
    | '/(app)/sessions'
    | '/(app)/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/(auth)/verify-email'
    | '/(error)/403'
    | '/(error)/404'
    | '/(error)/500'
    | '/(legal)/cookies'
    | '/(legal)/digital-independence'
    | '/(legal)/impressum'
    | '/(legal)/privacy-policy'
    | '/(legal)/terms'
    | '/api/health'
    | '/api/telemetry'
    | '/(app)/admin/audit-logs'
    | '/(app)/admin/schools'
    | '/(app)/admin/users'
    | '/api/auth/$'
    | '/(app)/admin/'
    | '/(app)/dashboard/'
    | '/(app)/admin/users/$userId'
    | '/api/users/me/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appPrivacyRoute: typeof appPrivacyRoute
  appProfileRoute: typeof appProfileRoute
  appSecurityRoute: typeof appSecurityRoute
  appSessionsRoute: typeof appSessionsRoute
  appSettingsRoute: typeof appSettingsRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  error403Route: typeof error403Route
  error404Route: typeof error404Route
  error500Route: typeof error500Route
  legalCookiesRoute: typeof legalCookiesRoute
  legalDigitalIndependenceRoute: typeof legalDigitalIndependenceRoute
  legalImpressumRoute: typeof legalImpressumRoute
  legalPrivacyPolicyRoute: typeof legalPrivacyPolicyRoute
  legalTermsRoute: typeof legalTermsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiTelemetryRoute: typeof ApiTelemetryRoute
  appAdminAuditLogsRoute: typeof appAdminAuditLogsRoute
  appAdminSchoolsRoute: typeof appAdminSchoolsRoute
  appAdminUsersRoute: typeof appAdminUsersRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  appAdminIndexRoute: typeof appAdminIndexRoute
  appDashboardIndexRoute: typeof appDashboardIndexRoute
  ApiUsersMeSessionsSessionIdRoute: typeof ApiUsersMeSessionsSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry': {
      id: '/api/telemetry'
      path: '/api/telemetry'
      fullPath: '/api/telemetry'
      preLoaderRoute: typeof ApiTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legal)/terms': {
      id: '/(legal)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof legalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legal)/privacy-policy': {
      id: '/(legal)/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof legalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legal)/impressum': {
      id: '/(legal)/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof legalImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legal)/digital-independence': {
      id: '/(legal)/digital-independence'
      path: '/digital-independence'
      fullPath: '/digital-independence'
      preLoaderRoute: typeof legalDigitalIndependenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legal)/cookies': {
      id: '/(legal)/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof legalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(error)/500': {
      id: '/(error)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof error500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(error)/404': {
      id: '/(error)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof error404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(error)/403': {
      id: '/(error)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof error403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/sessions': {
      id: '/(app)/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof appSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/security': {
      id: '/(app)/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof appSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/privacy': {
      id: '/(app)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof appPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard/': {
      id: '/(app)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof appDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/admin/': {
      id: '/(app)/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof appAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/admin/users': {
      id: '/(app)/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof appAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/admin/schools': {
      id: '/(app)/admin/schools'
      path: '/admin/schools'
      fullPath: '/admin/schools'
      preLoaderRoute: typeof appAdminSchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/admin/audit-logs': {
      id: '/(app)/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof appAdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/admin/users/$userId': {
      id: '/(app)/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof appAdminUsersUserIdRouteImport
      parentRoute: typeof appAdminUsersRoute
    }
    '/api/users/me/sessions/$sessionId': {
      id: '/api/users/me/sessions/$sessionId'
      path: '/api/users/me/sessions/$sessionId'
      fullPath: '/api/users/me/sessions/$sessionId'
      preLoaderRoute: typeof ApiUsersMeSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface appAdminUsersRouteChildren {
  appAdminUsersUserIdRoute: typeof appAdminUsersUserIdRoute
}

const appAdminUsersRouteChildren: appAdminUsersRouteChildren = {
  appAdminUsersUserIdRoute: appAdminUsersUserIdRoute,
}

const appAdminUsersRouteWithChildren = appAdminUsersRoute._addFileChildren(
  appAdminUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appPrivacyRoute: appPrivacyRoute,
  appProfileRoute: appProfileRoute,
  appSecurityRoute: appSecurityRoute,
  appSessionsRoute: appSessionsRoute,
  appSettingsRoute: appSettingsRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  error403Route: error403Route,
  error404Route: error404Route,
  error500Route: error500Route,
  legalCookiesRoute: legalCookiesRoute,
  legalDigitalIndependenceRoute: legalDigitalIndependenceRoute,
  legalImpressumRoute: legalImpressumRoute,
  legalPrivacyPolicyRoute: legalPrivacyPolicyRoute,
  legalTermsRoute: legalTermsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiTelemetryRoute: ApiTelemetryRoute,
  appAdminAuditLogsRoute: appAdminAuditLogsRoute,
  appAdminSchoolsRoute: appAdminSchoolsRoute,
  appAdminUsersRoute: appAdminUsersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  appAdminIndexRoute: appAdminIndexRoute,
  appDashboardIndexRoute: appDashboardIndexRoute,
  ApiUsersMeSessionsSessionIdRoute: ApiUsersMeSessionsSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
